"use client"

import * as React from "react"
import { GlassPanel } from "@/components/ui/glass-panel"
import { Sparkles, MessageSquare, ArrowRight, Zap, Bell } from "lucide-react"
import { Translate } from "@/features/i18n/hooks/useTranslation"
import { useLayoutStore } from "@/store/layoutStore"
import { useAIStore } from "@/features/ai/store/aiStore"
import { orchestrator } from "@/features/ai/engine/Orchestrator"

const QUICK_ACTIONS = [
  "Find Fastest Gate",
  "Nearest Restroom",
  "Least Crowded Food Court",
  "Accessible Route"
]

export function CopilotWidget() {
  const { setRightPanel, rightPanelOpen } = useLayoutStore()
  const { messages } = useAIStore()
  
  // Find the last recommendation generated by the AI
  const lastRecommendation = [...messages].reverse().find(m => m.recommendation)?.recommendation

  const handlePrompt = (prompt: string) => {
    if (!rightPanelOpen) {
      setRightPanel(true)
    }
    // Small delay to allow panel to animate open
    setTimeout(() => {
      orchestrator.ask(prompt)
    }, 100)
  }

  const openChat = () => {
    setRightPanel(true)
  }

  return (
    <GlassPanel className="relative overflow-hidden p-0 border border-ai-accent/30 shadow-[0_0_30px_rgba(91,140,255,0.15)] col-span-1 lg:col-span-2 group cursor-pointer transition-all hover:border-ai-accent/60" onClick={openChat}>
      {/* Ambient background glow */}
      <div className="absolute -inset-10 bg-gradient-to-br from-ai-accent/20 to-transparent opacity-50 blur-2xl group-hover:opacity-70 transition-opacity" />
      
      <div className="relative p-6 flex flex-col h-full z-10">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-ai-accent/20 rounded-xl">
              <Sparkles className="w-6 h-6 text-ai-accent" />
            </div>
            <div>
              <h2 className="font-display text-xl font-bold text-white tracking-tight">
                <Translate>AEGIS Copilot</Translate>
              </h2>
              <p className="text-sm text-ai-accent/80 font-medium">
                <Translate>Your intelligent stadium assistant</Translate>
              </p>
            </div>
          </div>
          <div className="h-10 w-10 rounded-full bg-white/5 flex items-center justify-center border border-white/10 group-hover:bg-white/10 transition-colors">
            <MessageSquare className="w-5 h-5 text-white" />
          </div>
        </div>

        <div className="flex-1">
          {lastRecommendation ? (
            <div className="bg-surface/50 border border-white/5 rounded-xl p-4 mb-4">
              <div className="flex items-center gap-2 mb-2 text-warning">
                <Bell className="w-4 h-4" />
                <span className="text-xs font-bold uppercase tracking-wider"><Translate>Active Suggestion</Translate></span>
              </div>
              <h3 className="font-semibold text-white text-sm mb-1">{lastRecommendation.title}</h3>
              <p className="text-muted-text text-xs line-clamp-2">{lastRecommendation.summary}</p>
            </div>
          ) : (
            <p className="text-muted-text text-sm mb-6 max-w-md">
              <Translate>I'm monitoring the stadium in real-time. How can I help make your match day better?</Translate>
            </p>
          )}
        </div>

        <div className="mt-auto">
          <div className="text-xs font-semibold text-muted-text uppercase tracking-wider mb-3">
            <Translate>Quick Actions</Translate>
          </div>
          <div className="flex flex-wrap gap-2">
            {QUICK_ACTIONS.map(action => (
              <button
                key={action}
                onClick={(e) => { e.stopPropagation(); handlePrompt(action); }}
                className="flex items-center gap-1.5 text-xs font-medium bg-white/5 hover:bg-ai-accent/20 border border-white/10 hover:border-ai-accent/50 text-white px-3 py-1.5 rounded-full transition-all"
              >
                <Zap className="w-3 h-3 text-ai-accent" />
                <Translate>{action}</Translate>
              </button>
            ))}
          </div>
        </div>
      </div>
    </GlassPanel>
  )
}
